name: Encrypt Shell Script (Android arm64-v8a)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - '1.sh'

jobs:
  cross-compile-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤1：安装基础依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf libtool git wget unzip

      # 步骤2：编译安装 shc（生成 C 源码）
      - name: Build and install SHC
        run: |
          git clone https://github.com/neurobin/shc.git
          cd shc
          automake --add-missing || true
          autoreconf -i
          ./configure
          make
          sudo make install

      # 步骤3：生成 C 源码（删除 x86 二进制）
      - name: Generate C source with SHC
        run: |
          shc -f 1.sh
          rm -f 1.sh.x
          ls -l

      # 步骤4：下载 Android NDK r23b
      - name: Download Android NDK r23b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O ndk.zip
          unzip -q ndk.zip

      # 步骤5：修复所有问题（空间+对齐）
      - name: Cross-compile to Android arm64-v8a
        run: |
          NDK_PATH="$(pwd)/android-ndk-r23b"
          ARM64_CLANG="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
     
           # 添加 -Wl,-z,max-page-size=64 和 -Wl,-z,common-page-size=64 参数
          $ARM64_CLANG -Wl,-z,max-page-size=64 -Wl,-z,common-page-size=64 -o 1.sh.x_android 1.sh.x.c -static -ldl
    
           # 验证二进制
           file 1.sh.x_android


      # 步骤6：上传最终产物
      - name: Upload Android binary & C source
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-encrypted
          path: |
            1.sh.x_android
            1.sh.x.c
