name: Encrypt Shell Script (Android arm64-v8a)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - '1.sh'

jobs:
  cross-compile-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf libtool git wget unzip

      - name: Build and install SHC
        run: |
          git clone https://github.com/neurobin/shc.git
          cd shc
          automake --add-missing || true
          autoreconf -i
          ./configure
          make
          sudo make install

      - name: Generate C source with SHC
        run: |
          shc -f 1.sh
          rm -f 1.sh.x
          ls -l

      - name: Download Android NDK r23b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O ndk.zip
          unzip -q ndk.zip

      - name: Cross-compile to Android arm64-v8a
        run: |
          NDK_PATH="$(pwd)/android-ndk-r23b"
          ARM64_CLANG="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
          
          $ARM64_CLANG \
            -o 1.sh.x_android \
            1.sh.x.c \
            -static \
            -O2 \
            -Wl,-z,max-page-size=64
          
          file 1.sh.x_android

      - name: Upload Android binary & C source
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-encrypted
          path: |
            1.sh.x_android
            1.sh.x.c
