name: Run script and upload customize.sh

on:
  workflow_dispatch:

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run start.sh
        run: |
          chmod +x start.sh
          ./start.sh

      - name: Upload customize.sh
        uses: actions/upload-artifact@v4
        with:
          name: customize-script
          path: customize.sh
          # 可选：设置artifact保留时间（天）
          retention-days: 7
